image: docker:20.10.16
services:
  - name: docker:20.10.16-dind
    alias: dind-service

stages:
  - lint
  - test
  - deploy

before_script:
  - apk update
  - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make curl npm
  - pip install docker-compose
  - npm install -g eslint

lint-test:
  stage: test
  script:
    - eslint .

integration-test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml build --no-cache
    - docker-compose -f docker-compose.yml up -d --remove-orphans
    - sleep 5
    - chmod +x api/test/endpoints.sh
    - ./api/test/endpoints.sh

deploy-app:
  stage: deploy
  environment: production
  script:
    - echo "If we were to automate the deployment, it would happen here."
