image: docker:latest
services:
  - docker:dind

stages:
  - lint
  - test
  - deploy

before_script:
  - apk update
  - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

lint-test:
  stage: test
  script:
    - echo "Running the linter"

integration-test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml build --no-cache
    - docker-compose -f docker-compose.yml up -d

deploy-app:
  stage: deploy
  environment: production
  script:
    - echo "If we were to automate the deployment, it would happen here."
