version: "3.8"

services:
  api:
    image: mq/api:latest
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "8083:8083"
    networks:
      - mqnet
  httpserv:
    image: mq/httpserv:latest
    build:
      dockerfile: Dockerfile
      context: ./httpserv
    ports:
      - "8978:8978"
    networks:
      - mqnet
    volumes:
      - mqlogs:/usr/app/logs
  imed:
    image: mq/imed:latest
    build:
      dockerfile: Dockerfile
      context: ./imed
    networks:
      - mqnet
    depends_on:
      rabmq:
          condition: service_healthy
  obse:
    image: mq/obse:latest
    build:
      dockerfile: Dockerfile
      context: ./obse
    networks:
      - mqnet
    volumes:
      - mqlogs:/usr/app/logs
    depends_on:
      rabmq:
        condition: service_healthy
  orig:
    image: mq/orig:latest
    build:
      dockerfile: Dockerfile
      context: ./orig
    networks:
      - mqnet
    depends_on:
      rabmq:
        condition: service_healthy
  rabmq:
    image: rabbitmq:3-management
    expose:
      - 5672
    networks:
      - mqnet
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

networks:
  mqnet:

volumes:
  mqlogs:
